/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/pedals/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Pedals */
    get: operations["get_pedals_api_v1_pedals__get"]
    put?: never
    /** Create Pedal */
    post: operations["create_pedal_api_v1_pedals__post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/pedals/{pedal_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Pedal */
    get: operations["get_pedal_api_v1_pedals__pedal_id__get"]
    put?: never
    post?: never
    /** Delete Pedal */
    delete: operations["delete_pedal_api_v1_pedals__pedal_id__delete"]
    options?: never
    head?: never
    /** Update Pedal */
    patch: operations["update_pedal_api_v1_pedals__pedal_id__patch"]
    trace?: never
  }
  "/health": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health Check */
    get: operations["health_check_health_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /**
     * PedalCreate
     * @example {
     *       "acquired_at": "2024-06-01",
     *       "brand": "Keeley Electronics",
     *       "img_url": "https://guitarhaus.ca/cdn/shop/files/Loomer-Workstation-Fuzz-Reverb-Angle-White-Keeley-Order-Switch-e1524689879106.jpg?v=1702250462&width=713",
     *       "name": "Keeley Loomer",
     *       "price": 299,
     *       "type": "gain"
     *     }
     */
    PedalCreate: {
      /** Name */
      name: string
      /** Brand */
      brand: string
      type: components["schemas"]["PedalType"]
      /** Price */
      price: number
      /**
       * Acquired At
       * Format: date
       */
      acquired_at: string
      /** Img Url */
      img_url?: string | null
    }
    /**
     * PedalPatch
     * @example {
     *       "img_url": "https://guitarhaus.ca/cdn/shop/files/Loomer-Workstation-Fuzz-Reverb-Angle-White-Keeley-Order-Switch-e1524689879106.jpg?v=1702250462&width=713",
     *       "price": 299
     *     }
     */
    PedalPatch: {
      /** Name */
      name?: string | null
      /** Brand */
      brand?: string | null
      type?: components["schemas"]["PedalType"] | null
      /** Price */
      price?: number | null
      /** Acquired At */
      acquired_at?: string | null
      /** Img Url */
      img_url?: string | null
    }
    /**
     * PedalType
     * @enum {string}
     */
    PedalType:
      | "gain"
      | "modulation"
      | "ambience"
      | "pitch"
      | "dynamics"
      | "other"
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  get_pedals_api_v1_pedals__get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
    }
  }
  create_pedal_api_v1_pedals__post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PedalCreate"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_pedal_api_v1_pedals__pedal_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        pedal_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_pedal_api_v1_pedals__pedal_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        pedal_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  update_pedal_api_v1_pedals__pedal_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        pedal_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PedalPatch"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  health_check_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
    }
  }
}
